### ISSUE TITLE
Cross-validation for time series data 

### ISSUE THREAD

**Issue by du-phan** [anthill/gip#3]
I just take a look at the notebook. I think that in the `Evaluation` section, we need to be more careful. We are dealing with time-series data so plain simple vanilla cross-validation is not a good option ( because CV will randomly pick data points for training set and testing set, so it is very likely that our training set contains points from the "future", and vice versa for your testing set). In short, we are borrowing information that we won't have in reality for training and thus our CV score will be over-optimistic. cf [here](http://stats.stackexchange.com/questions/14099/using-k-fold-cross-validation-for-time-series-model-selection) for more details.

**Comment by Asphahyre** [comment]
I see, that's also why I have graphs to show differences between real measures and predicted ones.
I don't really think that's so useless since it make us able to know if the model is more or less efficient, right?
However, it may influence strongly the features' importance, am I wrong?

**Comment by vallettea** [comment]
The idea i suggested on slack telling you to remove data from the training set is exactly about this. I have not checked the code yet but the training should never have seen any data from what we call future.

**Comment by du-phan** [comment]
The graphs are great. 

I didn't mean that the RMSE is useless. My point is that there is data leakage in your cross-validation process: your training set and testing set are no longer separated (there are some information of your training set in your testing set and vice versa), so your RMSE is misleading. You just need to find a way to compute the metrics correctly. 

I don't think that this problem influences the features' importance. Decision tree use a type of Gini/Information Gain score that depends only on the nature of the data, so even if there is data leakage, it won't affect these metrics.

**Comment by Asphahyre** [comment]
The fact is there isn't a feature depending on future data, so I don't really understand how learning in the future can "falsify" the results of the cross validation.
Each point of the curve will be fit independantly to each other, right?

**Comment by du-phan** [comment]
Independence is a very strong assumption here. The most important feature in your model is `Previous`, which correlates directly with the data point just before it. So it is better to avoid that term. Anyway, the good thing is that tree-based methods don't have any underlying statistical assumptions, that's not a big deal here. 

The problem with cross-validation here is not in the **features,** but in the **data** itself. Your model just can learn what you give it, in some sense it can not predict correctly what it haven't seen before. 

For example, supposing that until last week your data is quite stable, which means that it has a somehow identical pattern every day/week. Now imagine that the last weekend, there was some kind of huge festival going on in Arcachon, which resulted in a huuuge number of people that your model has never seen. Your model will probably still give a prediction that is quite high, but it will be no where near the real number, because it has never "explored"  that sample space, it doesn't know what is the shape of the curve. Now, supposing that you did a simple CV, in which some data points of the last weekend are "leaked" into your training set, then your model is now able to "learn" that situation, and thus it will give a much better prediction than it should. 

In general, if we can be sure that the structure of our data is invariant through time, then there will be no problem doing a simple CV. However, in time-series situation, we will never be sure when a bizarre event will occur, or when the pattern start to change (for example, when winter comes, how your model will adjust to it ?)

**Comment by vallettea** [comment]
@du-phan was right you were learning on all the dataset.
I pushed an updated version of your notebook with a lot of refactoring.
